Repository FRONTENDSCHOOL10/Topten, pull requests merged in 2024-09, with the labels that each got.

#10 Feature/password find/kbr
  Test.md
  src/components/Button/Button.module.scss
  src/components/Input/Input.module.scss
Labels: wontfix

#17 feat: 비밀번호 찾기 페이지 구현
  README.md
  package.json
  pnpm-lock.yaml
  src/components/Button/Button.jsx
  src/components/Button/Button.module.scss
  src/components/Button/Button_kbr.jsx
  src/components/Form/Form.jsx
  src/components/Input/Input.jsx
  src/components/Input/Input.module.scss
  src/components/Input/Input_kbr.jsx
  src/pages/FindPasswordPage.jsx
  src/styles/pages/FindPasswordPage.module.scss
Labels: enhancement, 구현(feature)

#18 Fix/develop/hsw 야무쌤 피드백 기반 기본 설정 수정
  README.md
Labels: 에러 수정

#15 feat : 로그인페이지 및 파비콘 추가
  README.md
  index.html
  public/icon/sc-favicon.png
  public/image/og-sc.png
  src/components/Input/Input.module.scss
  src/pages/LoginPage.jsx
  src/styles/pages/FindPasswordPage.module.scss
  src/styles/pages/Login.module.scss
Labels: 구현(feature)

#16 feat: Button컴포넌트 커스텀화 + IntroPage 작성
  README.md
  pnpm-lock.yaml
  src/components/Button/Button_hsw.jsx
  src/components/Button/Button_hsw.module.scss
  src/pages/IntroPage.jsx
  src/styles/pages/FindPasswordPage.module.scss
  src/styles/pages/IntroPage.module.scss
Labels: 구현(feature)

#19 Feature/header/hsw
  public/image/logo.png
  public/image/user-login.png
  src/components/Header/Header.jsx
  src/components/Header/Header.module.scss
  src/layouts/RootLayout.jsx
  src/styles/pages/FindPasswordPage.module.scss
Labels: 구현(feature)

#20 Feature/nav bar/hsw 하단 네비게이션 바 컴포넌트 제작
  README.md
  public/image/dock-icon-calendar.png
  public/image/dock-icon-home.png
  public/image/dock-icon-like.png
  public/image/dock-icon-lookbook.png
  public/image/dock-icon-mypage.png
  src/components/NavigationBar/NavigationBar.jsx
  src/components/NavigationBar/NavigationBar.module.scss
  src/layouts/RootLayout.jsx
Labels: 구현(feature), 완료

#22 feat: 세부 애니메이션 효과 조정
  src/pages/IntroPage.jsx
Labels: 구현(feature)

#29 비밀번호 찾기 페이지 리팩토링
  README.md
  src/components/Input/Input_kbr.jsx
  src/pages/FindPasswordPage.jsx
Labels: refactor

#34 비밀번호 찾기 페이지 스타일링 리팩토링
  README.md
  src/pages/FindPasswordPage.jsx
  src/styles/pages/FindPasswordPage.module.scss
  src/styles/utils/_theme.scss
  src/styles/utils/_utils.scss
Labels: refactor

#35 비밀번호 찾기 페이지 수정 및 룩북 컴포넌트 생성
  README.md
  src/components/Input/Input.module.scss
  src/components/Input/Input_kbr.jsx
  src/components/Main/LookBook.jsx
  src/components/Main/LookBook.module.scss
  src/components/Main/Product.jsx
  src/components/Main/Weather.jsx
  src/pages/MainPage.jsx
  src/styles/pages/FindPasswordPage.module.scss
  src/styles/pages/MainPage.module.scss
Labels: refactor

#40 feat : 로그인페이지 리팩토링
  README.md
  src/pages/LoginPage.jsx
  src/styles/pages/Login.module.scss
  src/styles/utils/_utils.scss
Labels: refactor

#43 Feature/costume card/hsw
  README.md
  package-lock.json
  package.json
  pnpm-lock.yaml
  public/image/icon-like-blank.png
  public/image/icon-like.png
  public/image/sample1.jpg
  public/image/sample2.jpg
  src/components/CostumeCard/CostumeCard.jsx
  src/components/CostumeCard/CostumeCard.module.scss
  src/components/CostumeCardManager/CostumeCardManager.jsx
  src/components/CostumeCardManager/CostumeCardManager.module.scss
  src/data/test.js
  src/pages/IntroPage.jsx
  src/pages/MainPage.jsx
  src/stores/likeStore.js
Labels: 진행중, 구현(feature)

#44 fix: 헤더의 프로필 사진 부분 빈공간 없도록 수정
  README.md
  src/components/Header/Header.module.scss
Labels: 에러 수정

#45 비밀번호 찾기 페이지 오류 수정 및 Button 컴포넌트 props 수정
  README.md
  src/components/Button/Button_kbr.jsx
  src/components/Input/Input.module.scss
  src/pages/FindPasswordPage.jsx
Labels: 에러 수정

#46 fix: 프로필이미지 클릭 시 마이페이지로 가도록 수정
  src/components/Header/Header.jsx
Labels: 에러 수정

#47 비밀번호 페이지 유효성 검사 수정
  README.md
  src/pages/FindPasswordPage.jsx
Labels: refactor

#49 fix: 버튼 타입 빠진 것 핫픽스
  README.md
  src/components/Button/Button.jsx
Labels: 에러 수정

#51 Fix/button/hsw
  src/components/Button/Button.jsx
Labels: 에러 수정

#52 Fix/header/hsw
  src/components/Header/Header.jsx
Labels: 에러 수정

#53 Input 컴포넌트 입력필드 범위 조정을 위한 조건부 스타일 추가
  README.md
  src/components/Input/Input.module.scss
  src/components/Input/Input_kbr.jsx
  src/components/Main/LookBook.jsx
Labels: wontfix

#54 fix: 로그인페이지 리팩토링
  README.md
  src/api/validation.js
  src/components/Input/Input.module.scss
  src/pages/LoginPage.jsx
Labels: refactor

#56 룩북 컴포넌트 1차 구현
  README.md
  src/components/Main/LookBook.jsx
  src/components/Main/LookBook.module.scss
  src/pages/FindPasswordPage.jsx
Labels: 구현(feature)

#58 Feature/costume card/hsw
  README.md
  src/components/CostumeCard/CostumeCard.jsx
  src/components/CostumeCard/CostumeCard.module.scss
  src/components/CostumeCardManager/CostumeCardManager.jsx
  src/components/CostumeCardManager/CostumeCardManager.module.scss
  src/hooks/.gitkeep
  src/hooks/useLikeSync.js
  src/layouts/RootLayout.jsx
  src/pages/CCM사용방법.jsx
  src/pages/IntroPage.jsx
  src/pages/LookbookPage.jsx
  src/pages/MainPage.jsx
  src/pages/MyPage.jsx
  src/pages/testpage.jsx
  src/stores/likeStore.js
  src/styles/utils/_utils.scss
Labels: 구현(feature), refactor

#61 feat: 위로가기 버튼 컴포넌트 구현 완료
  README.md
  src/components/ToTopButton/ToTopButton.jsx
  src/components/ToTopButton/ToTopButton.module.scss
  src/layouts/RootLayout.jsx
Labels: 구현(feature), 완료

#62 룩북 컴포넌트 수정
  README.md
  src/components/Main/LookBook.jsx
  src/components/Main/LookBook.module.scss
Labels: 구현(feature)

#65 CostumeCard 컴포넌트 레이아웃 수정
  README.md
  src/components/CostumeCard/CostumeCard.module.scss
  src/components/NavigationBar/NavigationBar.module.scss
Labels: wontfix

#67 feat: 현재 위치 중심으로 실시간 날씨 출력
  README.md
  package.json
  pnpm-lock.yaml
  public/icon/icon-lg-clear-day.png
  public/icon/icon-lg-clear-night.png
  public/icon/icon-lg-cloud-little-day.png
  public/icon/icon-lg-cloud-little-night.png
  public/icon/icon-lg-cloud-lot-day.png
  public/icon/icon-lg-cloud-lot-night.png
  public/icon/icon-lg-cloudy.png
  public/icon/icon-lg-rain_or_snow.png
  public/icon/icon-lg-rainy.png
  public/icon/icon-lg-shower.png
  public/icon/icon-lg-snow.png
  public/icon/icon-lg-thunder.png
  public/icon/icon-location.png
  public/icon/icon-sm-clear-day.png
  public/icon/icon-sm-clear-night.png
  src/components/Main/Weather.jsx
  src/components/Main/Weather.module.scss
Labels: 구현(feature)

#72 Feature/costume card manager/hsw
  README.md
  src/components/CostumeCardManager/CostumeCardManager.jsx
  src/components/Loader/Loader.jsx
  src/components/Loader/Loader.module.scss
  src/components/index.js
  src/hooks/useLikeSync.js
  src/layouts/RootLayout.jsx
  src/pages/MainPage.jsx
  src/pages/MyPage.jsx
  src/stores/likeStore.js
Labels: 구현(feature)

#74 룩북 페이지 1차 구현
  README.md
  src/components/Header/Header.module.scss
  src/pages/LookBookDetailPage.jsx
  src/pages/LookbookPage.jsx
  src/router.jsx
  src/styles/pages/LookbookDetailPage.module.scss
  src/styles/pages/Lookbookpage.module.scss
Labels: 진행중, 구현(feature)

#75 style: 보더 주석 처리
  src/styles/pages/Lookbookpage.module.scss
Labels: refactor

#79 Feature/like list/hsw
  README.md
  src/components/CostumeCardManager/CostumeCardManager.jsx
  src/hooks/useLikeSync.js
  src/layouts/RootLayout.jsx
  src/pages/MainPage.jsx
  src/pages/MyPage.jsx
  src/stores/likeStore.js
Labels: 완료, refactor

#81 feat: 시간대별 날씨 출력 (진행중)
  README.md
  public/icon/icon-lg-default.png
  public/icon/icon-sm-cloud-little-day.png
  public/icon/icon-sm-cloud-little-night.png
  public/icon/icon-sm-cloud-lot-day.png
  public/icon/icon-sm-cloud-lot-night.png
  public/icon/icon-sm-cloudy.png
  public/icon/icon-sm-rain-snow.png
  public/icon/icon-sm-rainy.png
  public/icon/icon-sm-shower.png
  public/icon/icon-sm-snow2.png
  public/icon/loading2.png
  src/components/Main/Weather.jsx
  src/components/Main/Weather.module.scss
Labels: 구현(feature)

#82 룩북 & 룩북 상세 페이지 2차 구현
  README.md
  src/components/Main/LookBook.jsx
  src/pages/LookBookDetailPage.jsx
  src/pages/LookbookPage.jsx
Labels: 진행중, 구현(feature)

#86 룩북 페이지 & 룩북 상세 페이지 3차 구현
  README.md
  src/components/Main/LookBook.jsx
  src/pages/FindPasswordPage.jsx
  src/pages/LookBookDetailPage.jsx
  src/pages/LookbookPage.jsx
  src/styles/pages/LookbookDetailPage.module.scss
  src/styles/pages/Lookbookpage.module.scss
Labels: 진행중, 구현(feature)

#90 Fix/router lookbook/hsw
  README.md
  src/pages/LookBookDetailPage.jsx
  src/pages/LookbookPage.jsx
  src/router.jsx
Labels: 수정

#91 Feature/likePage/hsw
  README.md
  src/components/CostumeCardManager/CostumeCardManager.jsx
  src/components/CostumeCardManager/CostumeCardManager.module.scss
  src/data/constant.js
  src/hooks/useLikeSync.js
  src/pages/LikedPage.jsx
  src/styles/pages/LikedPage.module.scss
Labels: 진행중, 구현(feature)

#84 Feature/modal/hsw 공통 모달컴포넌트 제작
  README.md
  src/components/CommonModal/CommonModal.jsx
  src/components/CommonModal/CommonModal.module.scss
  src/components/index.js
  src/pages/MainPage.jsx
Labels: 구현(feature)

#93 refactor: 날씨 정보 코드 개선
  README.md
  src/components/Main/Weather.jsx
  src/stores/weatherStore.js
  src/utils/weatherAPI.js
  src/utils/weatherIcons.js
  src/utils/weatherUtils.js
Labels: refactor

#95 Fix/refactoring/hsw
  README.md
  public/image/dock-icon-calendar.png
  public/image/dock-icon-home.png
  public/image/dock-icon-like.png
  public/image/dock-icon-lookbook.png
  public/image/dock-icon-mypage.png
  public/image/logo.png
  src/components/Button/Button.jsx
  src/components/Button/Button.module.scss
  src/components/Header/Header.module.scss
Labels: refactor

#96 fix: 시간대별 날씨 출력 오류 수정 / feat: 메인 접근시간 로컬스토리지 저장
  README.md
  src/pages/MainPage.jsx
  src/stores/weatherStore.js
  src/utils/weatherAPI.js
  src/utils/weatherUtils.js
Labels: 구현(feature), 수정

#101 feat: 날씨 데이터 객체로 묶기
  README.md
  src/stores/weatherStore.js
  src/utils/weatherAPI.js
  src/utils/weatherUtils.js
Labels: 구현(feature), 수정

#103 룩북 관련 페이지 리팩토링 & 계절 판별 로직 추가
  README.md
  src/components/Main/LookBook.jsx
  src/data/constant.js
  src/pages/LookBookDetailPage.jsx
  src/pages/LookbookPage.jsx
  src/styles/pages/LookbookDetailPage.module.scss
Labels: 구현(feature), refactor

#102 Feat/lazywithLoader/hsw
  README.md
  src/components/CostumeCard/CostumeCard.jsx
  src/components/CostumeCard/CostumeCard.module.scss
  src/components/CostumeCardManager/CostumeCardManager.jsx
  src/components/Loader/Loader.module.scss
  src/pages/Fallback.jsx
  src/pages/IntroPage.jsx
  src/pages/MainPage.jsx
  src/pages/index.js
  src/router.jsx
  src/styles/pages/Fallback.module.scss
Labels: refactor

#105 Feat/CalenderPage/hsw
  README.md
  src/components/Bookmark/Bookmark.jsx
  src/components/Bookmark/Bookmark.module.scss
  src/components/CostumeCard/CostumeCard.module.scss
  src/components/CostumeCardManager/CostumeCardManager.jsx
  src/components/CostumeCardManager/CostumeCardManager.module.scss
  src/components/index.js
  src/data/constant.js
  src/pages/CalendarPage.jsx
  src/styles/pages/CalendarPage.module.scss
  src/styles/pages/LikedPage.module.scss
Labels: 구현(feature)

#111 Feat/calendarpage/hsw
  src/components/Bookmark/Bookmark.jsx
  src/components/BookmarkModal/BookmarkModal.jsx
  src/components/BookmarkModal/BookmarkModal.module.scss
  src/components/CommonModal/CommonModal.module.scss
  src/components/Main/Product.jsx
  src/components/StarRate/StarRate.jsx
  src/components/index.js
  src/pages/CalendarPage.jsx
  src/pages/Calender.module.scss
  src/pages/MainPage.jsx
Labels: 구현(feature)

#109 날씨 캘린더 페이지 merge
  README.md
  package.json
  pnpm-lock.yaml
  src/components/Bookmark/Bookmark.jsx
  src/pages/CalendarPage.jsx
  src/pages/Calender.module.scss
  src/styles/pages/CalendarPage.module.scss
Labels: 진행중, 구현(feature)

#113 feat: 현재 접속경로에 따른 하단 네비게이션바 색상 활성화
  README.md
  public/image/dock-icon-calendar-active.png
  public/image/dock-icon-home-active.png
  public/image/dock-icon-like-active.png
  public/image/dock-icon-lookbook-active.png
  public/image/dock-icon-mypage-active.png
  src/components/NavigationBar/NavigationBar.jsx
Labels: 구현(feature)

#114 feat: CalendarPage 동작 로직 구현
  README.md
  src/components/Bookmark/Bookmark.jsx
  src/components/Bookmark/Bookmark.module.scss
  src/components/CostumeCardManager/CostumeCardManager.jsx
  src/components/CostumeCardManager/CostumeCardManager.module.scss
  src/components/StarRate/StarRate.jsx
  src/pages/CalendarPage.jsx
  src/pages/Calender.module.scss
Labels: 구현(feature)

#110 Feature/my page/ksh
  public/icon/camera.png
  public/icon/camera2.png
  public/icon/icon-button-close.png
  public/icon/picture.png
  src/api/getData.js
  src/components/NavList/NavList.jsx
  src/components/NavList/NavList.module.scss
  src/data/constant.js
  src/hooks/useGetUserInfo.js
  src/pages/ChangeColorPage.jsx
  src/pages/ChangeFitPage.jsx
  src/pages/ChangeMyInfoPage.jsx
  src/pages/ChangePasswordPage.jsx
  src/pages/CustomerServicePage.jsx
  src/pages/MyPage.jsx
  src/styles/pages/ChangeColorPage.module.scss
  src/styles/pages/ChangeFitPage.module.scss
  src/styles/pages/ChangePasswordPage.module.scss
  src/styles/pages/MainPage.module.scss
  src/styles/pages/changePage.module.scss
Labels: 수정

#117 Feat/auth zustand/hsw
  jsconfig.json
  src/components/Header/Header.jsx
  src/components/NavList/NavList.jsx
  src/components/index.js
  src/data/constant.js
  src/pages/MyPage.jsx
  src/stores/userStore.js
Labels: 구현(feature), refactor

#119 룩북 & 룩북 디테일 페이지 날씨 아이콘 수정
  README.md
  src/pages/CalendarPage.jsx
  src/pages/LookBookDetailPage.jsx
  src/pages/LookbookPage.jsx
Labels: 수정

#116 Refactor/product/ksh
  src/api/createData.js
  src/api/getData.js
  src/components/Main/Product.jsx
Labels: 수정

#112 style: 전반적인 스타일 교정
  README.md
  public/image/notification.png
  src/components/BookmarkModal/BookmarkModal.module.scss
  src/components/Button/Button.module.scss
  src/components/CommonModal/CommonModal.module.scss
  src/components/CostumeCardManager/CostumeCardManager.jsx
  src/components/CostumeCardManager/CostumeCardManager.module.scss
  src/components/CostumeCard_hjm/CostumeCard.jsx
  src/components/CostumeCard_hjm/CostumeCard.module.scss
  src/components/EditHeader/EditHeader.module.scss
  src/components/Header/Header.module.scss
  src/components/Input/Input.module.scss
  src/components/Main/LookBook.jsx
  src/components/Main/LookBook.module.scss
  src/components/Main/Product.jsx
  src/components/Main/Product.module.scss
  src/components/NavList/NavList.module.scss
  src/components/NavigationBar/NavigationBar.jsx
  src/components/NavigationBar/NavigationBar.module.scss
  src/components/RegisterCheckbox/RegisterCheckbox.module.scss
  src/components/Select/Select.module.scss
  src/components/ToTopButton/ToTopButton.module.scss
  src/components/index.js
  src/pages/CustomerServicePage.jsx
  src/pages/LoginPage.jsx
  src/pages/LookBookDetailPage.jsx
  src/pages/LookbookPage.jsx
  src/pages/MainPage.jsx
  src/pages/MyPage.jsx
  src/pages/RegisterPage.jsx
  src/stores/weatherStore.js
  src/styles/pages/CustomerServicePage.module.scss
  src/styles/pages/FindPasswordPage.module.scss
  src/styles/pages/LikedPage.module.scss
  src/styles/pages/Login.module.scss
  src/styles/pages/LookbookDetailPage.module.scss
  src/styles/pages/Lookbookpage.module.scss
  src/styles/pages/MainPage.module.scss
  src/styles/pages/RegisterPage.module.scss
  src/styles/utils/_utils.scss
Labels: 수정

#124 fix: lint에러 북마크의 속성 수정
  README.md
  src/components/Bookmark/Bookmark.jsx
  src/components/Bookmark/Bookmark.module.scss
Labels: 에러 수정

#127 sync: 동기화 위한 PR
  README.md
  src/components/Bookmark/Bookmark.jsx
  src/components/Bookmark/Bookmark.module.scss
  src/components/Button/Button.jsx
  src/components/Button/Button.module.scss
  src/components/Main/Product.jsx
  src/components/NavList/NavList.jsx
  src/data/constant.js
  src/pages/Calender.module.scss
  src/pages/MyPage.jsx
Labels: sync

#130 Feat/loading mainpage/hsw
  README.md
  src/components/LoadingComment/LoadingComment.jsx
  src/components/LoadingComment/LoadingComment.module.scss
  src/components/Main/Weather.jsx
  src/components/index.js
  src/pages/MainPage.jsx
  src/stores/weatherStore.js
  src/styles/pages/MainPage.module.scss
  src/utils/weatherAPI.js
  src/utils/weatherUtils.js
Labels: 수정

#126 Feature/my page/ksh
  src/api/getData.js
  src/api/updateData.js
  src/hooks/useGetUserInfo.js
  src/pages/ChangeColorPage.jsx
  src/pages/ChangeMyInfoPage.jsx
  src/pages/MyPage.jsx
  src/stores/userStore.js
Labels: 완료

#132 style: 공통, 메인 스타일 교정
  README.md
  src/components/CostumeCard_hjm/CostumeCard.module.scss
  src/components/Main/LookBook.module.scss
  src/components/Main/Product.module.scss
  src/components/Main/Weather.module.scss
  src/styles/utils/_utils.scss
Labels: 수정

#134 style: 룩북 페이지 교정
  README.md
  src/styles/pages/LookbookDetailPage.module.scss
  src/styles/pages/Lookbookpage.module.scss
Labels: 수정

#136 Feat/error/hsw
  README.md
  package.json
  pnpm-lock.yaml
  src/components/CostumeCardManager/CostumeCardManager.jsx
  src/components/CostumeCard_hjm/CostumeCard.jsx
  src/components/EditHeader/EditHeader.jsx
  src/components/LoadingComment/LoadingComment.jsx
  src/components/Main/LookBook.jsx
  src/components/Main/Weather.jsx
  src/pages/CCM사용방법.jsx
  src/pages/CalendarPage.jsx
  src/pages/Error.jsx
  src/pages/Fallback.jsx
  src/pages/LikedPage.jsx
  src/pages/MainPage.jsx
  src/pages/index.js
  src/pages/testpage.jsx
  src/router.jsx
  src/routes/CalendarPageWrapper.jsx
  src/routes/LikedPageWrapper.jsx
  src/routes/LookBookDetailPageWrapper.jsx
  src/routes/LookBookPageWrapper.jsx
  src/routes/MainPageWrapper.jsx
  src/styles/pages/Calendar.module.scss
  src/styles/pages/Error.module.scss
Labels: 구현(feature)

#137 style: 룩북 페이지 버튼, 좋아요 페이지 의상카드 교정
  README.md
  src/components/CostumeCard_hjm/CostumeCard.jsx
  src/components/CostumeCard_hjm/CostumeCard.module.scss
  src/styles/pages/LookbookDetailPage.module.scss
  src/styles/pages/Lookbookpage.module.scss
Labels: 수정

#121 Refactor/main/ksh
  README.md
  src/api/pbApi.js
  src/components/BookmarkModal/BookmarkModal.module.scss
  src/components/EditHeader/EditHeader.module.scss
  src/components/Main/Product.jsx
  src/data/constant.js
  src/hooks/useGetUserInfo.js
  src/pages/CalendarPage.jsx
  src/pages/ChangePasswordPage.jsx
  src/pages/MainPage.jsx
  src/pages/MyPage.jsx
  src/styles/pages/RegisterPage.module.scss
Labels: 완료

#141 refactor: 좋아요페이지 리팩토링
  README.md
  package.json
  pnpm-lock.yaml
  src/components/CostumeCardManager/CostumeCardManager.jsx
  src/components/CostumeCardManager/CostumeCardManager.module.scss
  src/components/CostumeCard_hjm/CostumeCard.module.scss
  src/components/Main/Weather.jsx
  src/pages/CalendarPage.jsx
  src/pages/LikedPage.jsx
  src/pages/MainPage.jsx
  src/pages/MyPage.jsx
  src/stores/index.js
  src/stores/weatherStore.js
Labels: 에러 수정, 수정

#142 style: 마이페이지 교정
  README.md
  public/icon/camera.png
  public/icon/camera2.png
  public/icon/picture.png
  src/components/EditHeader/EditHeader.module.scss
  src/styles/pages/MainPage.module.scss
Labels: 수정

#145 Refactor/product/ksh
  README.md
  src/api/createData.js
  src/components/BookmarkModal/BookmarkModal.jsx
  src/components/Main/Product.jsx
  src/components/Select/Select.jsx
  src/data/constant.js
  src/pages/ChangeColorPage.jsx
  src/pages/ChangeFitPage.jsx
  src/pages/ChangeMyInfoPage.jsx
  src/pages/ChangePasswordPage.jsx
  src/pages/MyPage.jsx
  src/pages/RegisterPage.jsx
Labels: 진행중

#149 hotfix: 좋아요 페이지 리팩토링(#141) 부분 재적용
  README.md
  package.json
  pnpm-lock.yaml
  src/components/CostumeCardManager/CostumeCardManager.jsx
  src/components/CostumeCardManager/CostumeCardManager.module.scss
  src/pages/LikedPage.jsx
Labels: 에러 수정, 수정

#152 fix: 북마크 저장 시 pbAuth 덮어쓰기 수정
  src/api/updateData.js
Labels: 완료

#151 style: 로그인페이지 교정
  README.md
  src/styles/pages/Login.module.scss
Labels: 수정

#154 Fix/LookbookPage/hsw
  README.md
  src/pages/LookbookPage.jsx
Labels: 에러 수정

#156 Update README.md
  README.md
Labels: documentation

#159 Fix/total/hsw
  src/pages/MainPage.jsx
Labels: 에러 수정

#160 fix/likedPage/hsw
  src/components/CostumeCardManager/CostumeCardManager.jsx
  src/hooks/useLikeSync.js
  src/pages/LikedPage.jsx
  src/pages/MainPage.jsx
  src/pages/MyPage.jsx
  src/stores/userStore.js
Labels: 에러 수정, 구현(feature)

#161 style: 캘린더 페이지 스타일 교정
  src/components/Bookmark/Bookmark.module.scss
  src/components/BookmarkModal/BookmarkModal.module.scss
  src/pages/CalendarPage.jsx
  src/styles/pages/Lookbookpage.module.scss
Labels: 수정

#168 refactor: 사용되지 않는 변수 삭제
  src/pages/FindPasswordPage.jsx
  src/pages/LookBookDetailPage.jsx
Labels: refactor
